-- Tiered company targeting: industry templates + enriched company metadata

create table if not exists industry_templates (
  id text primary key,
  name text not null,
  summary text not null default '',
  tooling text[] not null default '{}',
  domains text[] not null default '{}',
  methodologies text[] not null default '{}',
  role_patterns text[] not null default '{}',
  hiring_signals text not null default '',
  accent_color text not null default '#64748b',
  created_at timestamptz not null default now()
);

alter table companies add column if not exists industry_id text not null default 'consulting';
alter table companies add column if not exists data_source text not null default 'curated';
alter table companies add column if not exists region text not null default 'uk';
alter table companies add column if not exists is_featured boolean not null default false;
alter table companies add column if not exists last_verified_at timestamptz;
alter table companies add column if not exists created_by_user_id uuid references profiles(id) on delete set null;

create index if not exists companies_industry_id_idx on companies(industry_id);
create index if not exists companies_data_source_idx on companies(data_source);

insert into industry_templates (id, name, summary, tooling, domains, methodologies, role_patterns, hiring_signals, accent_color)
values
  ('fintech', 'Fintech & banking', 'Regulated financial products, payments, and platform engineering at pace.',
    array['AWS','Kubernetes','PostgreSQL','Java','Python','TypeScript','React','Kafka','Terraform'],
    array['fintech','banking','payments','compliance','platform'],
    array['Agile','product-led','incident response','continuous delivery'],
    array['software engineer','platform engineer','product manager','data engineer'],
    'Values ownership, regulatory awareness, and evidence of shipping in high-trust systems.', '#2563eb'),
  ('healthcare', 'Healthcare & life sciences', 'Clinical, digital health, and research systems with safety and privacy at the core.',
    array['Python','AWS','PostgreSQL','HL7','FHIR','React','TypeScript','Docker'],
    array['healthcare','clinical','digital health','research','compliance'],
    array['Agile','GDPR','clinical governance','user-centred design'],
    array['software engineer','data analyst','product manager','clinical informaticist'],
    'Prefers patient impact, data privacy literacy, and cross-functional clinical collaboration.', '#059669'),
  ('consulting', 'Consulting & professional services', 'Client delivery across transformation, technology, and advisory engagements.',
    array['Excel','PowerPoint','SQL','Python','Azure','AWS','Salesforce','Jira'],
    array['consulting','transformation','strategy','implementation','stakeholder management'],
    array['structured problem solving','workshops','Agile delivery','client management'],
    array['consultant','business analyst','project manager','technology consultant'],
    'Looks for structured thinking, client communication, and measurable engagement outcomes.', '#7c3aed'),
  ('retail-ecommerce', 'Retail & e-commerce', 'Omnichannel commerce, supply chain, and customer experience at scale.',
    array['Java','Python','AWS','PostgreSQL','React','TypeScript','Kubernetes','SQL'],
    array['retail','e-commerce','supply chain','merchandising','customer experience'],
    array['Agile','seasonal planning','A/B testing','continuous delivery'],
    array['software engineer','product manager','data analyst','operations manager'],
    'Wants commercial impact, operational awareness, and customer-centric delivery stories.', '#ea580c'),
  ('media-entertainment', 'Media & entertainment', 'Content platforms, streaming, and audience products with experimentation culture.',
    array['Python','Java','GCP','AWS','React','TypeScript','PostgreSQL','Kafka'],
    array['media','streaming','content','advertising','audience growth'],
    array['Agile','squads','experimentation','A/B testing'],
    array['software engineer','product manager','data engineer','content strategist'],
    'Prefers creative collaboration, experimentation, and audience or revenue impact.', '#db2777'),
  ('public-sector', 'Public sector & govtech', 'Digital public services with accessibility, reliability, and inclusive design.',
    array['Ruby','Python','AWS','PostgreSQL','Docker','React','TypeScript'],
    array['public sector','accessibility','service design','citizen services'],
    array['Agile','user research','service standards','continuous delivery'],
    array['software engineer','delivery manager','content designer','service designer'],
    'Values public impact, inclusive design, and evidence of service delivery.', '#1d70b8'),
  ('energy', 'Energy & utilities', 'Grid, renewables, and consumer energy products with operational reliability.',
    array['Python','SCADA','AWS','Azure','SQL','Java','IoT','GIS'],
    array['energy','utilities','renewables','operations','sustainability'],
    array['safety-first','operational excellence','Agile','asset management'],
    array['engineer','analyst','project manager','operations specialist'],
    'Expects safety awareness, operational rigour, and long-horizon project delivery.', '#ca8a04'),
  ('legal', 'Legal & compliance', 'Law firms and in-house teams blending legal expertise with technology.',
    array['Microsoft 365','SQL','document automation','React','Python','SharePoint'],
    array['legal','compliance','risk','contracts','regulatory'],
    array['matter management','quality review','client service','Agile'],
    array['paralegal','legal technologist','compliance analyst','knowledge manager'],
    'Values precision, confidentiality, and clear written communication.', '#475569'),
  ('education', 'Education & edtech', 'Learning platforms, assessment, and institutional digital transformation.',
    array['Python','JavaScript','React','PostgreSQL','AWS','LMS','Moodle'],
    array['education','edtech','learning','assessment','student experience'],
    array['pedagogy-led','user research','Agile','accessibility'],
    array['software engineer','instructional designer','product manager','education consultant'],
    'Prefers learner impact, inclusive design, and curriculum or platform delivery evidence.', '#0891b2'),
  ('manufacturing', 'Manufacturing & industrial', 'Production systems, supply chain, and industrial engineering at scale.',
    array['SAP','Python','SQL','CAD','PLC','Azure','IoT','Six Sigma'],
    array['manufacturing','supply chain','quality','operations','engineering'],
    array['Lean','Six Sigma','continuous improvement','safety-first'],
    array['engineer','operations manager','quality analyst','supply chain planner'],
    'Wants process improvement, quality metrics, and cross-functional production experience.', '#64748b'),
  ('telecom', 'Telecom & connectivity', 'Network infrastructure, consumer services, and large-scale platform operations.',
    array['Java','Python','Kubernetes','AWS','network automation','SQL','Linux'],
    array['telecom','network','infrastructure','B2C services','platform'],
    array['ITIL','on-call','Agile','incident management'],
    array['network engineer','software engineer','sre','product manager'],
    'Looks for reliability, scale, and operational ownership in complex systems.', '#4f46e5'),
  ('marketplace-logistics', 'Marketplace & logistics', 'Two-sided marketplaces, fulfilment, and real-time operational systems.',
    array['Go','Ruby','Python','AWS','Kubernetes','PostgreSQL','React','TypeScript'],
    array['marketplace','logistics','operations','mobile','consumer'],
    array['Agile','product-led','on-call','continuous delivery'],
    array['software engineer','operations manager','data analyst','product manager'],
    'Wants practical delivery in high-traffic, operationally complex products.', '#00ccbc')
on conflict (id) do update set
  name = excluded.name,
  summary = excluded.summary,
  tooling = excluded.tooling,
  domains = excluded.domains,
  methodologies = excluded.methodologies,
  role_patterns = excluded.role_patterns,
  hiring_signals = excluded.hiring_signals,
  accent_color = excluded.accent_color;

-- Refresh curated employers with industry metadata (catalog tier 1)
update companies set industry_id = 'fintech', data_source = 'curated', is_featured = true where id in ('monzo', 'revolut');
update companies set industry_id = 'media-entertainment', data_source = 'curated', is_featured = true where id = 'spotify';
update companies set industry_id = 'marketplace-logistics', data_source = 'curated', is_featured = true where id = 'deliveroo';
update companies set industry_id = 'public-sector', data_source = 'curated', is_featured = true where id = 'govuk';
update companies set industry_id = 'retail-ecommerce', data_source = 'curated', is_featured = true where id = 'amazon';

insert into companies (id, name, slug, accent_color, industry_id, data_source, region, is_featured, summary, tooling, domains, methodologies, role_patterns, hiring_signals, last_verified_at)
values
  ('starling', 'Starling Bank', 'starling', '#6935d3', 'fintech', 'curated', 'uk', true,
    'UK digital bank with strong engineering culture and in-house platform build.',
    array['Java','AWS','Kubernetes','PostgreSQL','React','TypeScript','Kafka'],
    array['fintech','banking','payments','mobile'],
    array['Agile','continuous delivery','ownership'],
    array['software engineer','mobile engineer','platform engineer'],
    'Prefers end-to-end ownership and regulated-environment delivery.', now()),
  ('wise', 'Wise', 'wise', '#9fe870', 'fintech', 'curated', 'uk', true,
    'International money movement with global engineering hubs and product-led growth.',
    array['Java','Python','AWS','Kubernetes','PostgreSQL','React','TypeScript'],
    array['fintech','payments','international','platform'],
    array['Agile','product-led','experimentation'],
    array['software engineer','product manager','data engineer'],
    'Values global scale stories and customer-centric product impact.', now()),
  ('bbc', 'BBC', 'bbc', '#000000', 'media-entertainment', 'curated', 'uk', true,
    'Public broadcaster building digital products for audiences at national scale.',
    array['Python','Java','AWS','React','TypeScript','PostgreSQL','Docker'],
    array['media','streaming','content','public service'],
    array['Agile','user research','accessibility','editorial collaboration'],
    array['software engineer','product manager','content designer','data analyst'],
    'Values public service impact, inclusive design, and editorial partnership.', now()),
  ('just-eat', 'Just Eat Takeaway', 'just-eat', '#ff8000', 'marketplace-logistics', 'curated', 'uk', false,
    'Food marketplace combining consumer apps with restaurant and logistics operations.',
    array['Java','Kotlin','AWS','Kubernetes','PostgreSQL','React','TypeScript'],
    array['marketplace','logistics','consumer','operations'],
    array['Agile','continuous delivery','product-led'],
    array['software engineer','mobile engineer','product manager'],
    'Looks for marketplace scale and cross-team delivery experience.', now()),
  ('nhs-digital', 'NHS England Digital', 'nhs-digital', '#005eb8', 'healthcare', 'curated', 'uk', true,
    'National health digital services with clinical safety and interoperability requirements.',
    array['Java','Python','AWS','PostgreSQL','React','HL7','FHIR'],
    array['healthcare','clinical','digital health','public sector'],
    array['Agile','clinical governance','GDPR','service design'],
    array['software engineer','delivery manager','clinical informaticist'],
    'Prefers patient impact, safety awareness, and cross-functional NHS delivery.', now()),
  ('tesco', 'Tesco', 'tesco', '#00539f', 'retail-ecommerce', 'curated', 'uk', true,
    'Omnichannel retail with supply chain, stores, and digital product engineering.',
    array['Java','Python','Azure','PostgreSQL','React','Kubernetes','SQL'],
    array['retail','e-commerce','supply chain','operations'],
    array['Agile','seasonal planning','continuous delivery'],
    array['software engineer','data analyst','product manager','operations manager'],
    'Wants commercial impact and operational awareness at national retail scale.', now()),
  ('accenture', 'Accenture', 'accenture', '#a100ff', 'consulting', 'curated', 'global', true,
    'Global consulting and technology delivery across transformation programmes.',
    array['Python','SQL','AWS','Azure','Salesforce','SAP','Power BI'],
    array['consulting','transformation','implementation','strategy'],
    array['structured problem solving','Agile delivery','client management'],
    array['consultant','technology consultant','business analyst','project manager'],
    'Looks for client communication, structured thinking, and delivery outcomes.', now()),
  ('deloitte', 'Deloitte', 'deloitte', '#86bc25', 'consulting', 'curated', 'global', false,
    'Professional services spanning advisory, audit, and technology implementation.',
    array['Excel','SQL','Python','Power BI','Azure','SAP'],
    array['consulting','risk','transformation','finance'],
    array['structured problem solving','workshops','stakeholder management'],
    array['consultant','analyst','project manager','technology consultant'],
    'Values analytical rigour, stakeholder management, and sector knowledge.', now()),
  ('bp', 'BP', 'bp', '#009a44', 'energy', 'curated', 'global', true,
    'Energy transition company blending traditional operations with digital and low-carbon tech.',
    array['Python','Azure','SAP','SQL','IoT','GIS'],
    array['energy','utilities','sustainability','operations'],
    array['safety-first','operational excellence','Agile'],
    array['engineer','analyst','project manager','operations specialist'],
    'Expects safety awareness and long-horizon operational project delivery.', now()),
  ('octopus-energy', 'Octopus Energy', 'octopus-energy', '#5840ff', 'energy', 'curated', 'uk', true,
    'Consumer energy tech with strong product engineering and data-driven operations.',
    array['Python','AWS','PostgreSQL','React','TypeScript','Kubernetes'],
    array['energy','consumer','platform','operations'],
    array['Agile','product-led','continuous delivery'],
    array['software engineer','data engineer','product manager'],
    'Prefers customer impact and fast iteration in regulated consumer markets.', now()),
  ('bt', 'BT Group', 'bt', '#5514b4', 'telecom', 'curated', 'uk', true,
    'Telecom infrastructure and consumer services with large-scale network operations.',
    array['Java','Python','Kubernetes','AWS','network automation','Linux'],
    array['telecom','network','infrastructure','B2C services'],
    array['ITIL','on-call','Agile','incident management'],
    array['network engineer','software engineer','sre','product manager'],
    'Looks for reliability, scale, and operational ownership.', now()),
  ('rolls-royce', 'Rolls-Royce', 'rolls-royce', '#002147', 'manufacturing', 'curated', 'uk', false,
    'Advanced engineering and manufacturing with aerospace and power systems.',
    array['CAD','SAP','Python','SQL','PLM','Six Sigma'],
    array['manufacturing','engineering','aerospace','quality'],
    array['Lean','Six Sigma','safety-first','continuous improvement'],
    array['engineer','quality analyst','project manager','operations manager'],
    'Wants engineering rigour, quality metrics, and complex programme delivery.', now()),
  ('pearson', 'Pearson', 'pearson', '#007fa3', 'education', 'curated', 'global', true,
    'Global learning company building assessment and education technology products.',
    array['Java','Python','AWS','React','TypeScript','PostgreSQL'],
    array['education','edtech','assessment','learning'],
    array['Agile','pedagogy-led','accessibility','user research'],
    array['software engineer','product manager','instructional designer'],
    'Prefers learner impact and inclusive product delivery.', now()),
  ('asos', 'ASOS', 'asos', '#2d2d2d', 'retail-ecommerce', 'curated', 'uk', false,
    'Fashion e-commerce with strong digital product and data teams.',
    array['C#','.NET','AWS','React','TypeScript','SQL','Kubernetes'],
    array['e-commerce','fashion','retail','personalisation'],
    array['Agile','A/B testing','continuous delivery'],
    array['software engineer','data analyst','product manager'],
    'Values commercial metrics and fast-paced digital retail delivery.', now())
on conflict (id) do update set
  name = excluded.name,
  industry_id = excluded.industry_id,
  data_source = excluded.data_source,
  is_featured = excluded.is_featured,
  summary = excluded.summary,
  tooling = excluded.tooling,
  domains = excluded.domains,
  methodologies = excluded.methodologies,
  role_patterns = excluded.role_patterns,
  hiring_signals = excluded.hiring_signals,
  last_verified_at = excluded.last_verified_at;
