import type { CompanyProfile } from '@/lib/companies';

/** Curated flagship employers — tier 1 catalog used when DB is empty or as seed data. */
export const CURATED_COMPANY_CATALOG: Omit<CompanyProfile, 'dataSource'>[] = [
  {
    id: 'monzo',
    name: 'Monzo',
    slug: 'monzo',
    logoUrl: '',
    accentColor: '#ff4f58',
    industryId: 'fintech',
    region: 'uk',
    isFeatured: true,
    summary: 'Digital bank scaling cloud-native product engineering across mobile and platform teams.',
    tooling: ['AWS', 'Kubernetes', 'Go', 'Python', 'PostgreSQL', 'Terraform', 'CI/CD', 'React', 'TypeScript'],
    domains: ['fintech', 'banking', 'payments', 'mobile', 'platform'],
    methodologies: ['Agile', 'product-led', 'incident response', 'pairing'],
    rolePatterns: ['platform engineer', 'backend engineer', 'mobile engineer', 'sre', 'product manager'],
    hiringSignals: 'Values ownership, customer impact, and evidence of shipping in regulated environments.',
  },
  {
    id: 'revolut',
    name: 'Revolut',
    slug: 'revolut',
    logoUrl: '',
    accentColor: '#0075ff',
    industryId: 'fintech',
    region: 'uk',
    isFeatured: true,
    summary: 'Global fintech with fast-moving product squads and strong emphasis on delivery velocity.',
    tooling: ['Java', 'Kotlin', 'Python', 'AWS', 'Kubernetes', 'PostgreSQL', 'Kafka', 'React', 'TypeScript'],
    domains: ['fintech', 'payments', 'crypto', 'banking', 'growth'],
    methodologies: ['Agile', 'data-driven', 'cross-functional squads'],
    rolePatterns: ['software engineer', 'devops engineer', 'data engineer', 'product analyst'],
    hiringSignals: 'Looks for breadth, speed, and measurable outcomes across product and ops.',
  },
  {
    id: 'starling',
    name: 'Starling Bank',
    slug: 'starling',
    logoUrl: '',
    accentColor: '#6935d3',
    industryId: 'fintech',
    region: 'uk',
    isFeatured: true,
    summary: 'UK digital bank with strong engineering culture and in-house platform build.',
    tooling: ['Java', 'AWS', 'Kubernetes', 'PostgreSQL', 'React', 'TypeScript', 'Kafka'],
    domains: ['fintech', 'banking', 'payments', 'mobile'],
    methodologies: ['Agile', 'continuous delivery', 'ownership'],
    rolePatterns: ['software engineer', 'mobile engineer', 'platform engineer'],
    hiringSignals: 'Prefers end-to-end ownership and regulated-environment delivery.',
  },
  {
    id: 'wise',
    name: 'Wise',
    slug: 'wise',
    logoUrl: '',
    accentColor: '#9fe870',
    industryId: 'fintech',
    region: 'uk',
    isFeatured: true,
    summary: 'International money movement with global engineering hubs and product-led growth.',
    tooling: ['Java', 'Python', 'AWS', 'Kubernetes', 'PostgreSQL', 'React', 'TypeScript'],
    domains: ['fintech', 'payments', 'international', 'platform'],
    methodologies: ['Agile', 'product-led', 'experimentation'],
    rolePatterns: ['software engineer', 'product manager', 'data engineer'],
    hiringSignals: 'Values global scale stories and customer-centric product impact.',
  },
  {
    id: 'spotify',
    name: 'Spotify',
    slug: 'spotify',
    logoUrl: '',
    accentColor: '#1db954',
    industryId: 'media-entertainment',
    region: 'global',
    isFeatured: true,
    summary: 'Product and platform org focused on experimentation, data, and large-scale consumer systems.',
    tooling: ['Java', 'Python', 'GCP', 'Kubernetes', 'React', 'TypeScript', 'PostgreSQL', 'Kafka'],
    domains: ['consumer', 'streaming', 'recommendations', 'platform', 'data'],
    methodologies: ['Agile', 'squads', 'experimentation', 'A/B testing'],
    rolePatterns: ['backend engineer', 'data engineer', 'ml engineer', 'product manager'],
    hiringSignals: 'Prefers impact stories, experimentation, and collaboration across squads.',
  },
  {
    id: 'bbc',
    name: 'BBC',
    slug: 'bbc',
    logoUrl: '',
    accentColor: '#000000',
    industryId: 'media-entertainment',
    region: 'uk',
    isFeatured: true,
    summary: 'Public broadcaster building digital products for audiences at national scale.',
    tooling: ['Python', 'Java', 'AWS', 'React', 'TypeScript', 'PostgreSQL', 'Docker'],
    domains: ['media', 'streaming', 'content', 'public service'],
    methodologies: ['Agile', 'user research', 'accessibility', 'editorial collaboration'],
    rolePatterns: ['software engineer', 'product manager', 'content designer', 'data analyst'],
    hiringSignals: 'Values public service impact, inclusive design, and editorial partnership.',
  },
  {
    id: 'deliveroo',
    name: 'Deliveroo',
    slug: 'deliveroo',
    logoUrl: '',
    accentColor: '#00ccbc',
    industryId: 'marketplace-logistics',
    region: 'uk',
    isFeatured: true,
    summary: 'Marketplace engineering with logistics, real-time systems, and mobile-first product delivery.',
    tooling: ['Ruby', 'Go', 'Python', 'AWS', 'Kubernetes', 'PostgreSQL', 'React', 'TypeScript'],
    domains: ['marketplace', 'logistics', 'mobile', 'operations', 'consumer'],
    methodologies: ['Agile', 'product-led', 'on-call', 'continuous delivery'],
    rolePatterns: ['software engineer', 'devops engineer', 'mobile engineer', 'data analyst'],
    hiringSignals: 'Wants practical delivery stories in high-traffic, operationally complex products.',
  },
  {
    id: 'just-eat',
    name: 'Just Eat Takeaway',
    slug: 'just-eat',
    logoUrl: '',
    accentColor: '#ff8000',
    industryId: 'marketplace-logistics',
    region: 'uk',
    isFeatured: false,
    summary: 'Food marketplace combining consumer apps with restaurant and logistics operations.',
    tooling: ['Java', 'Kotlin', 'AWS', 'Kubernetes', 'PostgreSQL', 'React', 'TypeScript'],
    domains: ['marketplace', 'logistics', 'consumer', 'operations'],
    methodologies: ['Agile', 'continuous delivery', 'product-led'],
    rolePatterns: ['software engineer', 'mobile engineer', 'product manager'],
    hiringSignals: 'Looks for marketplace scale and cross-team delivery experience.',
  },
  {
    id: 'govuk',
    name: 'GOV.UK',
    slug: 'govuk',
    logoUrl: '',
    accentColor: '#1d70b8',
    industryId: 'public-sector',
    region: 'uk',
    isFeatured: true,
    summary: 'Public-sector digital services with accessibility, reliability, and user-centred design at the core.',
    tooling: ['Ruby', 'Python', 'AWS', 'PostgreSQL', 'Docker', 'React', 'TypeScript'],
    domains: ['public sector', 'accessibility', 'service design', 'platform'],
    methodologies: ['Agile', 'user research', 'service standards', 'continuous delivery'],
    rolePatterns: ['software engineer', 'platform engineer', 'delivery manager', 'content designer'],
    hiringSignals: 'Values public impact, inclusive design, and clear evidence of service delivery.',
  },
  {
    id: 'nhs-digital',
    name: 'NHS England Digital',
    slug: 'nhs-digital',
    logoUrl: '',
    accentColor: '#005eb8',
    industryId: 'healthcare',
    region: 'uk',
    isFeatured: true,
    summary: 'National health digital services with clinical safety and interoperability requirements.',
    tooling: ['Java', 'Python', 'AWS', 'PostgreSQL', 'React', 'HL7', 'FHIR'],
    domains: ['healthcare', 'clinical', 'digital health', 'public sector'],
    methodologies: ['Agile', 'clinical governance', 'GDPR', 'service design'],
    rolePatterns: ['software engineer', 'delivery manager', 'clinical informaticist'],
    hiringSignals: 'Prefers patient impact, safety awareness, and cross-functional NHS delivery.',
  },
  {
    id: 'amazon',
    name: 'Amazon',
    slug: 'amazon',
    logoUrl: '',
    accentColor: '#ff9900',
    industryId: 'retail-ecommerce',
    region: 'global',
    isFeatured: true,
    summary: 'Large-scale distributed systems, ownership culture, and customer-obsessed engineering.',
    tooling: ['Java', 'Python', 'AWS', 'DynamoDB', 'Kubernetes', 'TypeScript', 'SQL'],
    domains: ['e-commerce', 'cloud', 'logistics', 'platform', 'retail'],
    methodologies: ['ownership', 'operating reviews', 'bar raiser', 'Agile'],
    rolePatterns: ['software development engineer', 'sde', 'devops engineer', 'product manager'],
    hiringSignals: 'Expects STAR-style impact, ownership, and deep technical depth for level.',
  },
  {
    id: 'tesco',
    name: 'Tesco',
    slug: 'tesco',
    logoUrl: '',
    accentColor: '#00539f',
    industryId: 'retail-ecommerce',
    region: 'uk',
    isFeatured: true,
    summary: 'Omnichannel retail with supply chain, stores, and digital product engineering.',
    tooling: ['Java', 'Python', 'Azure', 'PostgreSQL', 'React', 'Kubernetes', 'SQL'],
    domains: ['retail', 'e-commerce', 'supply chain', 'operations'],
    methodologies: ['Agile', 'seasonal planning', 'continuous delivery'],
    rolePatterns: ['software engineer', 'data analyst', 'product manager', 'operations manager'],
    hiringSignals: 'Wants commercial impact and operational awareness at national retail scale.',
  },
  {
    id: 'accenture',
    name: 'Accenture',
    slug: 'accenture',
    logoUrl: '',
    accentColor: '#a100ff',
    industryId: 'consulting',
    region: 'global',
    isFeatured: true,
    summary: 'Global consulting and technology delivery across transformation programmes.',
    tooling: ['Python', 'SQL', 'AWS', 'Azure', 'Salesforce', 'SAP', 'Power BI'],
    domains: ['consulting', 'transformation', 'implementation', 'strategy'],
    methodologies: ['structured problem solving', 'Agile delivery', 'client management'],
    rolePatterns: ['consultant', 'technology consultant', 'business analyst', 'project manager'],
    hiringSignals: 'Looks for client communication, structured thinking, and delivery outcomes.',
  },
  {
    id: 'deloitte',
    name: 'Deloitte',
    slug: 'deloitte',
    logoUrl: '',
    accentColor: '#86bc25',
    industryId: 'consulting',
    region: 'global',
    isFeatured: false,
    summary: 'Professional services spanning advisory, audit, and technology implementation.',
    tooling: ['Excel', 'SQL', 'Python', 'Power BI', 'Azure', 'SAP'],
    domains: ['consulting', 'risk', 'transformation', 'finance'],
    methodologies: ['structured problem solving', 'workshops', 'stakeholder management'],
    rolePatterns: ['consultant', 'analyst', 'project manager', 'technology consultant'],
    hiringSignals: 'Values analytical rigour, stakeholder management, and sector knowledge.',
  },
  {
    id: 'bp',
    name: 'BP',
    slug: 'bp',
    logoUrl: '',
    accentColor: '#009a44',
    industryId: 'energy',
    region: 'global',
    isFeatured: true,
    summary: 'Energy transition company blending traditional operations with digital and low-carbon tech.',
    tooling: ['Python', 'Azure', 'SAP', 'SQL', 'IoT', 'GIS'],
    domains: ['energy', 'utilities', 'sustainability', 'operations'],
    methodologies: ['safety-first', 'operational excellence', 'Agile'],
    rolePatterns: ['engineer', 'analyst', 'project manager', 'operations specialist'],
    hiringSignals: 'Expects safety awareness and long-horizon operational project delivery.',
  },
  {
    id: 'octopus-energy',
    name: 'Octopus Energy',
    slug: 'octopus-energy',
    logoUrl: '',
    accentColor: '#5840ff',
    industryId: 'energy',
    region: 'uk',
    isFeatured: true,
    summary: 'Consumer energy tech with strong product engineering and data-driven operations.',
    tooling: ['Python', 'AWS', 'PostgreSQL', 'React', 'TypeScript', 'Kubernetes'],
    domains: ['energy', 'consumer', 'platform', 'operations'],
    methodologies: ['Agile', 'product-led', 'continuous delivery'],
    rolePatterns: ['software engineer', 'data engineer', 'product manager'],
    hiringSignals: 'Prefers customer impact and fast iteration in regulated consumer markets.',
  },
  {
    id: 'bt',
    name: 'BT Group',
    slug: 'bt',
    logoUrl: '',
    accentColor: '#5514b4',
    industryId: 'telecom',
    region: 'uk',
    isFeatured: true,
    summary: 'Telecom infrastructure and consumer services with large-scale network operations.',
    tooling: ['Java', 'Python', 'Kubernetes', 'AWS', 'network automation', 'Linux'],
    domains: ['telecom', 'network', 'infrastructure', 'B2C services'],
    methodologies: ['ITIL', 'on-call', 'Agile', 'incident management'],
    rolePatterns: ['network engineer', 'software engineer', 'sre', 'product manager'],
    hiringSignals: 'Looks for reliability, scale, and operational ownership.',
  },
  {
    id: 'rolls-royce',
    name: 'Rolls-Royce',
    slug: 'rolls-royce',
    logoUrl: '',
    accentColor: '#002147',
    industryId: 'manufacturing',
    region: 'uk',
    isFeatured: false,
    summary: 'Advanced engineering and manufacturing with aerospace and power systems.',
    tooling: ['CAD', 'SAP', 'Python', 'SQL', 'PLM', 'Six Sigma'],
    domains: ['manufacturing', 'engineering', 'aerospace', 'quality'],
    methodologies: ['Lean', 'Six Sigma', 'safety-first', 'continuous improvement'],
    rolePatterns: ['engineer', 'quality analyst', 'project manager', 'operations manager'],
    hiringSignals: 'Wants engineering rigour, quality metrics, and complex programme delivery.',
  },
  {
    id: 'pearson',
    name: 'Pearson',
    slug: 'pearson',
    logoUrl: '',
    accentColor: '#007fa3',
    industryId: 'education',
    region: 'global',
    isFeatured: true,
    summary: 'Global learning company building assessment and education technology products.',
    tooling: ['Java', 'Python', 'AWS', 'React', 'TypeScript', 'PostgreSQL'],
    domains: ['education', 'edtech', 'assessment', 'learning'],
    methodologies: ['Agile', 'pedagogy-led', 'accessibility', 'user research'],
    rolePatterns: ['software engineer', 'product manager', 'instructional designer'],
    hiringSignals: 'Prefers learner impact and inclusive product delivery.',
  },
  {
    id: 'asos',
    name: 'ASOS',
    slug: 'asos',
    logoUrl: '',
    accentColor: '#2d2d2d',
    industryId: 'retail-ecommerce',
    region: 'uk',
    isFeatured: false,
    summary: 'Fashion e-commerce with strong digital product and data teams.',
    tooling: ['C#', '.NET', 'AWS', 'React', 'TypeScript', 'SQL', 'Kubernetes'],
    domains: ['e-commerce', 'fashion', 'retail', 'personalisation'],
    methodologies: ['Agile', 'A/B testing', 'continuous delivery'],
    rolePatterns: ['software engineer', 'data analyst', 'product manager'],
    hiringSignals: 'Values commercial metrics and fast-paced digital retail delivery.',
  },
];

export function curatedCatalogAsProfiles(): CompanyProfile[] {
  return CURATED_COMPANY_CATALOG.map((company) => ({ ...company, dataSource: 'curated' as const }));
}
